/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConvertOptions: typeof import('./src/components/ConvertOptions.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    ErrorAlert: typeof import('./src/components/ErrorAlert.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    ModeSelector: typeof import('./src/components/ModeSelector.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PlayerChecker: typeof import('./src/components/PlayerChecker.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RootDirSelector: typeof import('./src/components/RootDirSelector.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
